# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details
# used Silverstripe Translatable as a guide

language: php
php:
 - 5.4

sudo: false

env:
 - DB=MYSQL CORE_RELEASE=3.3 PDO=1

matrix:
  include:
   - php: 5.5
     env: DB=PGSQL CORE_RELEASE=3.2

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
# Execute tests
 - vendor/bin/phpunit email-helpers/tests/
